version: 0.1
phases:
  build:
    commands:
      - $(aws ecr get-login)
      - $(echo "cd $SRC_PATH") && docker build --tag "$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)" .
      - $(echo "cd $SRC_PATH") && docker tag "$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)" "${REPOSITORY_URI}:$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - $(echo "cd $SRC_PATH") && docker push "${REPOSITORY_URI}"
      - printf '{"version":"%s"}' "$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)" > version.json
artifacts:
  files: version.json
