AWSTemplateFormatVersion: '2010-09-09'
Description: Service1 ECR repository
Parameters:

  RepositoryName:
    Type: String
    Description: RepositoryName

Resources:

  ##############################
  # ECR Repository
  ##############################

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName