AWSTemplateFormatVersion: '2010-09-09'
Description: JobDefinition
Parameters:

  AppName:
    Type: String
    Description: App Name

  Environment:
    Type: String
    Description: Environment

  JobName:
    Type: String
    Description: Job Name

  BatchStack:
    Type: String
    Description: Batch Stack

  VPCStack:
    Type: String
    Description: VPC Stack Name

  Vcpus:
    Type: Number
    Description: Vcpu's to use
    Default: 2

  Memory:
    Type: Number
    Description: Memory to use
    Default: 2048

  RetryNumber:
    Type: Number
    Description: How many times to retry a batch job
    Default: 3

  RepositoryUrl:
    Type: String
    Description: RepositoryUrl

  BuildVersion:
    Type: String
    Description: Latest build version

  Version:
    Type: String
    Default: ''
    Description: Service version

Conditions:
  UseBuildVersion: !Or
    - !Equals [!Ref Environment, 'dev']
    - !Equals [!Ref Version, '']

Resources:

  JobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: !Sub "${JobName}-${Environment}"
      Type: container
      RetryStrategy:
        Attempts: !Ref RetryNumber
      ContainerProperties:
        Image: !Sub
          - "${URL}:${Version}"
          - {
            URL: !Ref RepositoryUrl,
            Version: {"Fn::If": ["UseBuildVersion", {"Ref": "BuildVersion"}, { "Ref": "Version" }]}
          }
        Vcpus: !Ref Vcpus
        Memory: !Ref Memory
        JobRoleArn:
          Fn::ImportValue:
            !Sub "${BatchStack}-TaskRole"
        MountPoints:
          - ContainerPath: "/scratch"
            ReadOnly: false
            SourceVolume: docker_scratch
        Volumes:
          - Name: docker_scratch
            Host:
              SourcePath: "/docker_scratch"

Outputs:
  JobDefinition:
    Value: !Ref JobDefinition
    Export:
      Name: !Sub '${AWS::StackName}-JobDefinition'